import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]

live_config_reload = true

[font]
size = 12.0

[font.bold]
family = "Liga SFMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Liga SFMono Nerd Font"
style = "Bold Italic"

[font.normal]
family = "Liga SFMono Nerd Font"
style= "Regular" 

[window]
padding.x = 10
padding.y = 15
class.instance = "Alacritty"
class.general = "Alacritty"
decorations = "none"

[cursor]
blink_interval = 550
unfocused_hollow = true
thickness = 0.15
